feat: adiciona arquivo yml

diff --git a/.github/workflows/dotnet-build.yml b/.github/workflows/dotnet-build.yml
--- a/.github/workflows/dotnet-build.yml
+++ b/.github/workflows/dotnet-build.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
   schedule:
-    - cron: '0 * * * *' 
+    - cron: '0 * * * *'  # Executa a cada hora
 
 jobs:
   build:
@@ -20,13 +20,20 @@ jobs:
       with:
         node-version: '16'
 
+    - name: Verify package.json presence
+      run: |
+        if [ ! -f package.json ]; then
+          echo "package.json not found in the root directory."
+          exit 1
+        fi
+
     - name: Install dependencies
       run: npm install
 
     - name: Run tests
       run: npm test
 
-    - name: Mostra Horario Atual  
-      run: 
+    - name: Mostra Horario Atual
+      run: |
         echo "Mostrando horario atual..."
         echo "Horario Atual é $(date)"
